### ISSUE TITLE
[English]: Missing words

### ISSUE THREAD

**Issue by mpfaff** [languagetool-language-server/vscode-languagetool#27]
I've noticed some words that are missing.

* hadron(s)/anti-hadron(s)
* Keras
* expandability
* soilization

**Comment by davidlday** [comment]
Please see #25

**Comment by mpfaff** [comment]
Hi @davidlday. I'm very sorry to hear about that.

I'm confused about where it gets valid English words from. Could you point me to where I can report these?

**Comment by davidlday** [comment]
Hi @mpfaff  - 

No worries. I should have given this issue a little more thought. LanguageTool Linter isn't ready yet, but should be soon. But the first release won't have custom dictionaries in it.

In the meantime, you might check out [LTeX](https://github.com/valentjn/vscode-ltex), as I believe it allows you to add words to a local dictionary. And if it works for you, stick with it.

As for where the valid words come from, they come from [LanguageTool](https://github.com/languagetool-org/languagetool) itself, which I believe uses the Hunspell libraries. You can check on their repo, maybe open an issue, but I don't believe they customize those dictionaries either.

Good luck, and peace.

**Comment by mpfaff** [comment]
Hi @davidlday

I've installed LTeX and it had the same issue. It seems that the en_CA dictionary is missing those words. For now, I'm managing with the en_US dictionary, but it's not a permanent solution, due to word differences like color -> colour. 

Thanks for the help.
